sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    # yml格式的配置文件中，对数字和字符串格式的数据有一定要求：
    # 1. 字符串类型的数据需要加双引号
    # 2. 数字类型的数据不需要加双引号
    # 3. 布尔类型的数据需要小写
    # 4. 如果字符串中包含特殊字符（如冒号、逗号等），以0b、0、0x开头的数字（会被按照二、八、十六进制解析），需要加双引号
    password: "04126"
